eureka:
  client:
    serviceUrl:
      defaultZone: https://julia-eureka-service.herokuapp.com/eureka

server:
  port: 8012

sessions:
  security:
    tokenKey: Bearer
    tokenLifeTime: 30

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

spring:
  application:
    name: authentication-service
  resources:
    add-mappings: true
