logging:
  level:
    org:
      hibernate: debug
spring:
  datasource:
    password: 28c6008234e93984204dccb2127d776802be55dccc6df427f213e800ada639e4
    url: jdbc:postgresql://ec2-46-137-121-216.eu-west-1.compute.amazonaws.com:5432/d2sefft705feu0
    username: tdxnwkeymjsxsl
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
        format_sql: true
