eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
server:
  port: ${PORT:8080}
spring:
  application:
    name: eureka-service
