eureka:
  client:
    serviceUrl:
      defaultZone: https://julia-eureka-service.herokuapp.com/eureka

server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers:
              - "SecurityToken"
              - "userId"
              - "FileName"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true